### ISSUE TITLE
Incorrect spoiler arm information in Takeoff Checklist

### ISSUE THREAD

**Issue by sdreagan** [Community-A-4E/community-a4e-c#645]
The takeoff checklist on the Kneeboard (Page 5-3) instructs folks to turn the spoilers off. This is incorrect, they should be Armed. When taking off from an airfield the spoilers should normally be Armed. When armed, the spoilers at idle power are up, perpendicular with the wing and "spoiling lift". As you takeoff you push power to MIL, the RPM increases through 70% and the spoilers fall flush with the wing no longer spoiling lift. Only then do you commence your takeoff roll. Then if you need to abort the takeoff for any reason, you reduce power to idle and apply brakes gradually at first... as RPM decreases through 70% the spoilers spring up again spoiling lift which increases weight on the landing gear, improving brake performance, and also reduces the adverse effects of any crosswind.

**Comment by callmepartario** [comment]
i'll make sure this change makes it into the next release.
