### ISSUE TITLE
not a bug report I don't think

### ISSUE THREAD

**Issue by Woodchip44** [Community-A-4E/community-a4e-c#658]
**Describe the bug**
I used the CTS app by HomeFries to load and run the A-4E-C module for a large list of key mappings defined for this module.  I am using TrackIR5 and the CTS app is configured for it.  I launched the A-4E-C module in DCS and it seems okay until I try to use some of the keybindings.  Opening the "Adjust control" options to check some of the keybindings, I found that some are missing and some are not correct.  For example the H1 hat on the joystick should be for trimming Pitch and Roll but it shows to be for slow view up, down and left, right.  But they do not work as mapped.  A few of the bindings do work but they are the ones used mostly by default.

I have no problems with the other modules including the F-5E Tiger II.

I have checked a few of the discord sites but no replies.
I can not find a current link to HomeFries,  This issue may be something that can be corrected on that end.
I am hoping someone has seen this before and point me in the right direction.

**To Reproduce**
1.  '...'  Load the CTS app after installing the A-4E-C  module and config it to include the A-4E-C module and also config to use TrackIR5.  This means the H1 button on my Thrustmaster Wart Hog joystick will use H1 for trimming pitch and roll controls.
2. Next try the H1 in free flight to see if they function for trimming the pitch or roll controls. Mine do not trim any thing, if fact the H1 button does nothing.
3. Click on '....' Go the the "Adjust Controls" in the DCS control section and check how they are defined, in my configuration they are defined to view slow for what ever direction the H1 button is pushed
4.  '....'The only errors I found in the DCS log file are as follows
2024-08-03 23:34:32.574 ERROR_ONCE DX11BACKEND (205228): render target 'mainDepthBuffer' not found
2024-08-03 23:34:32.666 ERROR_ONCE DX11BACKEND (205228): render target 'uiTargetColor' not found
2024-08-03 23:34:32.666 ERROR_ONCE DX11BACKEND (205228): render target 'uiTargetDepth' not found

Did not see any errors in the DCS.log
 
**Expected behavior**
Could not trim the pitch or roll of the aircraft since CTS is configured to use TrackIR5 thus setting the H1 button to function for trimming the pitch and roll.

**Software Information (please complete the following information):**
 - DCS Version: [DCS 2.9.6.58056]
 - A-4E Version [Version 2.2-beta - 23 Oct 2023]

**Additional context**
The following is from what I think would be the CTS log file called  " efm-log.txt "

Root A-4E-C Folder: C:\Users\Dave\Saved Games\DCS\Mods\aircraft\A-4E-C
Path: C:\Users\Dave\Saved Games\DCS\Mods\aircraft\A-4E-C\entry.lua 
Checking entry.lua, Hash: e2836311dce613c5e7dd3263241c1332b2335631
Verified: entry.lua, Hash: e2836311dce613c5e7dd3263241c1332b2335631
Path: C:\Users\Dave\Saved Games\DCS\Mods\aircraft\A-4E-C\A-4E-C.lua 
Checking A-4E-C.lua, Hash: 49b4bf497c2101dc05fa7bb0eb4d6243fc1af358
Verified: A-4E-C.lua, Hash: 49b4bf497c2101dc05fa7bb0eb4d6243fc1af358
Path: C:\Users\Dave\Saved Games\DCS\Mods\aircraft\A-4E-C\Cockpit/Scripts/EFM_Data_Bus.lua 
Checking Cockpit/Scripts/EFM_Data_Bus.lua, Hash: 27c51d1abd20ee831d315e90727260d0e89ce0f7
Verified: Cockpit/Scripts/EFM_Data_Bus.lua, Hash: 27c51d1abd20ee831d315e90727260d0e89ce0f7
Path: C:\Users\Dave\Saved Games\DCS\Mods\aircraft\A-4E-C\Entry/Suspension.lua 
Checking Entry/Suspension.lua, Hash: 3d4322ed63e5b38cb2e811888501a464c83eb523
Verified: Entry/Suspension.lua, Hash: 3d4322ed63e5b38cb2e811888501a464c83eb523
Releasing Components...
Closing Log...

Thanks for any help or pointing me in the right direction......

woodchip44

**Comment by callmepartario** [comment]
support for the use of alternate installers must be handled by the developers of said installer.
