### ISSUE TITLE
Screen goes black when looking at radar panel 

### ISSUE THREAD

**Issue by 3DaniToJa** [Community-A-4E/community-a4e-c#670]
**Describe the bug**
Might be for people woth integrated graphics card only. Whenever the radar screen would be visible on screen, the entire monitor goes black, even if it appears in the corner of the screen.

**Expected behavior**
Game shouldn't go all blank when looking at a single piece of MFD/TID

**Screenshots**
I'll send of needed via discord. 

**Software Information (please complete the following information):**
 - DCS Version: steam edition latest version openbeta
 - A-4E Version 2.2

**Additional context**
Even if fixing it entirely isn't possible instantly, is there at least a hot fix? To maybe disable the whole screen for the player or whatever.

**Comment by callmepartario** [comment]
duplicate, see #598

**Comment by 3DaniToJa** [comment]
Thank you, I've checked it. I'm loading in the main game to see if old radar panel special setting will help.

**Comment by callmepartario** [comment]
cool, please direct any further information to the original thread so all information can be in in one, succinct place.

**Comment by 3DaniToJa** [comment]
> cool, please direct any further information to the original thread so all information can be in in one, succinct place.

Just did yesterday, seems like I've gathered the most data possible
